apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a-unique-name-for-your-docs
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: production
  owner: my-awesome-team
